export const SOCIAL_PLATFORMS = [
  { id: 'facebook', name: 'Facebook', icon: 'fa-brands fa-facebook', color: '#1877F2' },
  { id: 'twitter', name: 'Twitter/X', icon: 'fa-brands fa-x-twitter', color: '#000000' },
  { id: 'instagram', name: 'Instagram', icon: 'fa-brands fa-instagram', color: '#E4405F' },
  { id: 'linkedin', name: 'LinkedIn', icon: 'fa-brands fa-linkedin', color: '#0A66C2' },
  { id: 'youtube', name: 'YouTube', icon: 'fa-brands fa-youtube', color: '#FF0000' },
  { id: 'tiktok', name: 'TikTok', icon: 'fa-brands fa-tiktok', color: '#000000' },
  { id: 'github', name: 'GitHub', icon: 'fa-brands fa-github', color: '#181717' },
  { id: 'discord', name: 'Discord', icon: 'fa-brands fa-discord', color: '#5865F2' },
  { id: 'twitch', name: 'Twitch', icon: 'fa-brands fa-twitch', color: '#9146FF' },
  { id: 'pinterest', name: 'Pinterest', icon: 'fa-brands fa-pinterest', color: '#E60023' },
  { id: 'reddit', name: 'Reddit', icon: 'fa-brands fa-reddit', color: '#FF4500' },
  { id: 'snapchat', name: 'Snapchat', icon: 'fa-brands fa-snapchat', color: '#FFFC00' },
  { id: 'telegram', name: 'Telegram', icon: 'fa-brands fa-telegram', color: '#26A5E4' },
  { id: 'whatsapp', name: 'WhatsApp', icon: 'fa-brands fa-whatsapp', color: '#25D366' },
  { id: 'spotify', name: 'Spotify', icon: 'fa-brands fa-spotify', color: '#1DB954' },
  { id: 'medium', name: 'Medium', icon: 'fa-brands fa-medium', color: '#000000' },
  { id: 'behance', name: 'Behance', icon: 'fa-brands fa-behance', color: '#1769FF' },
  { id: 'dribbble', name: 'Dribbble', icon: 'fa-brands fa-dribbble', color: '#EA4C89' },
  { id: 'slack', name: 'Slack', icon: 'fa-brands fa-slack', color: '#4A154B' },
  { id: 'patreon', name: 'Patreon', icon: 'fa-brands fa-patreon', color: '#FF424D' },
  { id: 'paypal', name: 'PayPal', icon: 'fa-brands fa-paypal', color: '#00457C' },
  { id: 'venmo', name: 'Venmo', icon: 'fa-brands fa-venmo', color: '#3D95CE' },
  { id: 'cashapp', name: 'Cash App', icon: 'fa-solid fa-dollar-sign', color: '#00D632' },
  { id: 'apple', name: 'Apple', icon: 'fa-brands fa-apple', color: '#000000' },
  { id: 'amazon', name: 'Amazon', icon: 'fa-brands fa-amazon', color: '#FF9900' },
  { id: 'etsy', name: 'Etsy', icon: 'fa-brands fa-etsy', color: '#F45800' },
  { id: 'shopify', name: 'Shopify', icon: 'fa-brands fa-shopify', color: '#96BF48' },
  { id: 'substack', name: 'Substack', icon: 'fa-solid fa-newspaper', color: '#FF6719' },
  { id: 'website', name: 'Website', icon: 'fa-solid fa-globe', color: '#6366f1' },
  { id: 'email', name: 'Email', icon: 'fa-solid fa-envelope', color: '#6366f1' },
  { id: 'phone', name: 'Phone', icon: 'fa-solid fa-phone', color: '#6366f1' },
  { id: 'custom', name: 'Custom', icon: 'fa-solid fa-link', color: '#6B7280' },
];